name:                h99
version:             0.1.0.0
github:              "leoslf/H-99"
license:             BSD3
author:              "Leo Sin"
maintainer:          "leo.sin@my.cityu.edu.hk"
copyright:           "2022 Leo Sin"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/h99#readme>

dependencies:
- base >= 4.7 && < 5
- random >= 1.2
- containers >= 0.6

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-name-shadowing
- -Wno-type-defaults
- -Wno-missing-export-lists

library:
  source-dirs: src

executables:
  h99-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - h99
    when:
    - condition: false
      other-modules: Paths_h99

tests:
  h99-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - h99
    - hspec >= 2
    - QuickCheck >= 2.14
    - combinatorial >= 0.1
